name: Make_All
on: [push, pull_request, workflow_dispatch]
jobs:
  Make_All:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install golang
      - run: chmod ugo+x make.sh && ./make.sh
      - run: echo "v0.1-rc" >> "$GITHUB_OUTPUT"
        id: version_check
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.version_check.outputs.TAG_NAME}}
          files: |
            ./build/*.pdf
            ./build/*.html

