name: Make_All
on: [push, pull_request, workflow_dispatch]
jobs:
  Make_All:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
           sudo apt-get install lua5.3 weasyprint
           sudo apt-get purge weasyprint
      - run: PATH="./:$PATH" PYTHONPATH="./WeasyPrint-60.2:./pydyf-0.8.0:$PYTHONPATH" lua ./make.lua
      - run: echo "v0.1-rc" >> "$GITHUB_OUTPUT"
        id: version_check
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.version_check.outputs.TAG_NAME}}
          files: |
            ./build/*.pdf
            ./build/*.html

